dataset: cubes
scene: manstar
cubes_filename: "datasets/cubes/crops.pt"
val_cubes_filename : "datasets/cubes/crops.pt"
# tmp_file_dir: "/home/ethanweber/temp" # TODO(ethan): implement this
batch_size: 16
val_batch_size: 4

noise_scheduler: "ddpm"
num_train_timesteps: 1000
num_inference_steps: 100 # NOTE: setting small for fast tests
corrupt_max_timesteps: 400

save_images_locally: True